name: 'Interactive Bolt'
tags: ['IB']
setup_command: 'bash setup.sh'
command: "mkdir temp"
is_parent: False
sla_exempt: True
priority: 1
project_id: j595
resources:
    docker_image: docker.apple.com/afm/torch:3.11-20230706
    timeout: 7d
    task_type: 1gpu
    num_nodes: 1
    ports: [NOTEBOOK_PORT, BOLT_TAB_TensorBoard]
    rdma: false
    cluster: gcp2
cluster_options:
    gcp:
        instance_type: a2-ultragpu-8g


#name: 'Interactive Bolt'
#tags: ['IB']
#setup_command:
#command: "mkdir temp"
#is_parent: False
#sla_exempt: True
#priority: 1
#project_id: j595
##resources:
##  cluster: aws_1
##  #docker_image: docker.apple.com/coreflow/ubuntu20.04-cuda11.8-torch:10.0.0-nv22.09
##  docker_image: docker.apple.com/iris/iris:latest
##  #docker_image: docker.apple.com/ajax/triton-ft-backend-bolt:23.04-20230530-ajax-gpt
##  memory_gb: 32
##  num_cpus: 8
##  num_gpus: 1
##  timeout: 7d
##  disk_gb: 1024
#resources:
#  task_type: 4gpu
#  num_gpus: 4
#  num_cpus: 20
#  memory_gb: 180
#  disk_gb: 500
##cluster_options:
##  gcp:
##    instance_type: p4d.24xlarge



